name = "bitz-vpn"
main = "build/worker/shim.mjs"
compatibility_date = "2024-05-23"
minify = true
workers_dev = true

[[kv_namespaces]]
binding = "SIREN"
id = "06b589583c0c49e7a986f0aeed880487"
[build]
command = "cargo install -q worker-build && worker-build --release"

[env.dev]
build = { command = "cargo install -q worker-build && worker-build --dev" }

[vars]
UUID = "aaaaaaa1-bbbb-4ccc-accc-eeeeeeeeeee1"
MAIN_PAGE_URL = "https://raw.githubusercontent.com/bitzblack/Bitz-VPN/refs/heads/master/web/index.html"
SUB_PAGE_URL = "https://raw.githubusercontent.com/bitzblack/Bitz-VPN/refs/heads/master/web/sub.html"
LINK_PAGE_URL = "https://raw.githubusercontent.com/bitzblack/Bitz-VPN/refs/heads/master/web/link.html"
